#!groovy

// Generated by IBM TransformationAdvisor
// Tue Mar 19 13:18:56 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}