#!groovy

// Generated by IBM TransformationAdvisor
// Wed Mar 20 09:50:42 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}